### ISSUE TITLE
How to get ItemDetails?

### ISSUE THREAD

**Issue by IzaacJ** [Kryszak/gwatlin#1]
Hello.

Using this to build a tool for my guild, but having issues getting details about an item.

F.ex if the item I've fetched is an armor piece, how do I get the details for it, like which kind of armor piece it is (head, shoulders, coat etc), weight class, etc etc,

If those details aren't available for all the item types I'd not call the Items api to be done.
Details are found here: https://wiki.guildwars2.com/wiki/API:2/items

**Comment by Kryszak** [comment]
I just released version 1.1 with fix - ItemDetails can be retrieved as a map. I currently don't have much time to do something more on this - so any pull requests with improvements are welcome :smiley:
