### ISSUE TITLE
Switch from Gson to kotlinx.serialization

### ISSUE THREAD

**Issue by fanonwue** [Kryszak/gwatlin#28]
We are currently using Gson for our deserialization needs. According to the [Github project](https://github.com/google/gson) it's now in maintenance mode and can be considered deprecated. Quote: 'Gson is currently in maintenance mode'.

I propse switching to the official serialization library kotlinx.serialization as a replacement.

Another alternative would be [Moshi](https://github.com/square/moshi), but I'd prefer going with the more "native" solution.

**Comment by Kryszak** [comment]
`kotlinx.serialization` seems fine. As for me, anything that plays nice with fuel library and fits into current codebase will do just fine.

**Comment by fanonwue** [comment]
It has an [extension package](https://fuel.gitbook.io/documentation/deserialization/fuel-kotlinx-serialization) for `kotlinx.serialization`, so that should be fine.

**Comment by Kryszak** [comment]
Let's go with standard serialization then.

**Comment by fanonwue** [comment]
Update on this: I've kinda hit a road block. The library doesn't use reflection, which isn't a bad thing of course. But it has problems determining the correct serializer for generic collections when using it with Fuel. This is also something that's mentioned in the docs for the extension package. Even the simple methods that just deserialize a JSON array to a list of strings doesn't work. It does work when I'm more specific as to which serializer it's supposed to use, like creating a `getRequestList` function that explicitly returns a list of type `T`.

I'll try to fix it over the next days for some hours, but if I can't get it to work then we'd either have to rework the internal HTTP client or use another library, like Moshi. Didn't think a lack of reflection would be a bad thing...

**Comment by fanonwue** [comment]
Another update: I've found a possible solution. Like I mentioned, the problem is that `kotlinx.serialization` doesn't use reflection. Even with reified generics that Kotlin offers, there isn't enough information to determine the correct serializer that needs to be used to produce, for example, a `List<String>` when just providing the type via `T`.

It is possible to explicitly pass in a `DeserializationStrategy<T>`, which is basically the deserializer to use. For example, if we alter the `getRequest()` method to look like this:
```kotlin
protected inline fun <reified T : Any> getRequest(uri: String, deserializer: DeserializationStrategy<T>, language: ApiLanguage? = null, configBlock: Request.() -> Unit = {}): T {
    val (_, response, result) = "$baseUrl/$uri"
        .httpGet()
        .also { addDefaultHeaders(it, language) }
        .also { log.info(logMessage.format(it.url)) }
        .also { configBlock(it) }
        .responseObject<T>(deserializer, json)

    return processResult(result, ErrorResponse(response, RetrieveError.serializer()))
```
and then adjust all internal API client functions to call it in this manner:
```kotlin
fun getLegendIds() = getRequest(legendsEndpoint, ListSerializer(String.serializer()))
```
or
```kotlin
fun getLegends(ids: List<String>, language: ApiLanguage?): List<Legend> {
    val params = ids.joinToString(",")
    return getRequest("$legendsEndpoint?ids=$params", ListSerializer(Legend.serializer()), language)
}
```
it works perfectly fine, as the library doesn't have to guess the deserializer to use, which is not possible without reflection.

On one hand, there's the obvious downside of adding more boilerplate code and increasing the overall complexity. On the other hand, this means that we aren't relying on reflection anymore, which can cause weird bugs when trying to use something like GraalVM-Native for example.

The alternative would be to use Moshi, like I mentioned before. This works very similar to how Gson works, and should work fine without having to alter the code in this way.

I am honestly not sure about which path we should take. My personal preference would still be `kotlinx.serialization`, but it's obviously more work to transition to (I'd still be doing it) and does some bigger alterations to the codebase.

**Comment by Kryszak** [comment]
I'd say simpler way with Moshi would not introduce a lot of changes to code approach.
As for GraalVM possible issues: there should already be reportings of any issues with that with current implementation, so for now we should not have any problems. 
If we want to tackle native Graal vm binaries I'd say it would be better to introduce some kind of unstable/experimental branch and work on that there, with possible separate release version.

**Comment by fanonwue** [comment]
Hmmm looks like Moshi requires the use of Kotlin SymbolProcessor (KSP) for code generation, which means we'd have to introduce more dependencies and compiler plugins. I'm still more inclined to go with `kotlinx.serialization`, but if you prefer Moshi, we can go with that.

**Comment by Kryszak** [comment]
Let's just say I'm not a fan of SymbolProcessor approach. I still don't really like boilerplate that `serialization` will bring, but it needs to be done only once so it shouldn't be *that* bad.
