### ISSUE TITLE
Outdated Kotlin version

### ISSUE THREAD

**Issue by fanonwue** [Kryszak/gwatlin#8]
The project is using Kotlin 1.3.50 right now, which is several years old by now. I propose updating to a newer version (1.8.10 at this time) to benefit from the several improvmenets made to both the language and kotlinc.

This shouldn't impact any user of this library as we can still target Java 8 bytecode if needed. I could open a PR for this if there isn't any objection to this.

Might as well switch to the Kotlin DSL that Gradle offers, which is something I personally prefer. It's a Kotlin project after all, right?

**Comment by Kryszak** [comment]
As for Kotlin version sure, best to be up to date. It would be good to pull up the Java target version too to last LTS (17) or at least 11.

For the Kotlin DSL - that's neutral for me, groovy DSL tends to have better Intellij support in terms of syntax, but Kotlin one is fine too.

**Comment by Kryszak** [comment]
I had some time today and so I bumped most of project dependencies in PR linked to this issue. For remaining deps (spock, groovy, JDK 17) I created separate issue. 

I didn't migrate from Groovy to Kotlin DSL for Gradle, so feel free to do so if you want.

**Comment by Kryszak** [comment]
Issue for DSL migration continued in https://github.com/Kryszak/gwatlin/issues/12
